### PR TITLE
file monitoring on OSX + minor changes

### PR DESCRIPTION
**Pull request by chipselecta**
Hi Steven,

First, let me say, very exciting project!

inotify isn't available on OSX, so I added support for fsevent.  For future reference, I later discovered Listen, which looks like it might be the preferred way to do cross-platform file monitoring:

https://github.com/guard/listen

I also made the following minor changes:
- was calling Log.warning instead of Log.warn
- added --udp-port for the STUN/uTP UDP socket
- ConnectionManager.have_connection? was calling non-existent Connection.active?  I added Connection.authenticated? and used that instead.

Best,
Cotton

### CODE REVIEW

**Comment by jewel** [comment]
Hello Cotton,

Thanks for your contribution!  The "listen" gem does look like a much better approach.  Originally, my plan was going to be to stick to ruby's stdlib as much as possible, since each gem that's added can complicate release packaging for all of the platforms that we'd like to support.  However, it seems silly to repeat the work that the guard project has already done to get filesystem notifications for each platform.  I have added switching to the "listen" gem to my todo list.

I'm not sure why I never added `Connection.active?`  It is supposed to use `@timeout_at` to eventually drop dead connections.  In any case, the connection manager needs a lot of work in order to work in real-world conditions, and  your change is a good improvement.

I don't have OS X to test on yet so I'm glad to have someone try it on that platform.

Steven

**Comment by chipselecta** [comment]
Hi Steven,

Thanks for accepting the changes!  I like the principle of keeping the requirements as simple as possible.  Listen seems to have the advantage of supporting all the major platforms.

Ah, that makes sense.  I wasn't sure about the active? change, but better than crashing at least.  I figured that dropped connections got deleted, so wouldn't show up as authenticated/active.  As for OS X, basic syncing between OS X and Linux seems to work for me now.

Speaking of a todo list, do you have one you can share?  I'd like to contribute further.  Browsing the code, I saw some things that need doing, but I think it makes sense to coordinate.

Cotton

**Comment by jewel** [comment]
I've been keeping a list in trello, but it is full of minutia without having a lot of the bigger items:

https://trello.com/b/FoZeuqTJ/clearskies

Any contribution that you're willing to make will be appreciated.  I don't mind receiving email, so you can coordinate details with me by emailing clearskies@stevenjewel.com.  I'm not easily offended, so feel free to be frank about what you think needs to be improved.

I think a good short-term goal should be to get releases made for Windows, OS X, and Linux.  This would make it easier for non-programmers to try out the project.

**Comment by jewel** [comment]
Would you be willing to relicense these changes under the LGPL instead of the GPL?  More details in [this file](https://github.com/jewel/clearskies/blob/master/license-change.md).

There seem to be two github accounts involved with this pull request, @chipselecta and @cseed.

**Pull request merged**
